//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AL_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Homepage
    {
        public int Id { get; set; }
        public string Title01 { get; set; }
        public string Content01 { get; set; }
        public string Title02 { get; set; }
        public string Content02 { get; set; }
        public string Title03 { get; set; }
        public string Content03 { get; set; }
        public string Picture01 { get; set; }
        public string Title04 { get; set; }
        public string SubTitle01 { get; set; }
        public string TextTitle01 { get; set; }
        public string Text01 { get; set; }
        public string TextTitle02 { get; set; }
        public string Text02 { get; set; }
        public string TextTitle03 { get; set; }
        public string Text03 { get; set; }
        public string TextTitle04 { get; set; }
        public string Text04 { get; set; }
        public string TextTitle05 { get; set; }
        public string Text05 { get; set; }
        public string TextTitle06 { get; set; }
        public string Text06 { get; set; }
        public string Title05 { get; set; }
        public string SubTitle02 { get; set; }
        public string Title06 { get; set; }
        public string SubTitle03 { get; set; }
        public string Picture02 { get; set; }
        public string Picture03 { get; set; }
        public string Picture04 { get; set; }
    }
}
