//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AL_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Mission
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string SubContentTitle01 { get; set; }
        public string SubContent01 { get; set; }
        public string SubContentTitle02 { get; set; }
        public string SubContent02 { get; set; }
        public string SubContentTitle03 { get; set; }
        public string SubContent03 { get; set; }
    }
}
