//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AL_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Product
    {
        public int Id { get; set; }
        public string CareerTitle { get; set; }
        public string CareerContent { get; set; }
        public string BusinessTitle { get; set; }
        public string BusinessContent { get; set; }
    }
}
