//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AL_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompanyEntities : DbContext
    {
        public CompanyEntities()
            : base("name=CompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Project> C_Project { get; set; }
        public virtual DbSet<C_About> C_About { get; set; }
        public virtual DbSet<C_Mission> C_Mission { get; set; }
        public virtual DbSet<C_Policy> C_Policy { get; set; }
        public virtual DbSet<C_Contact> C_Contact { get; set; }
        public virtual DbSet<C_News> C_News { get; set; }
        public virtual DbSet<C_Recruitment> C_Recruitment { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<C_Slider> C_Slider { get; set; }
        public virtual DbSet<C_Homepage> C_Homepage { get; set; }
        public virtual DbSet<C_Product> C_Product { get; set; }
    }
}
